//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: api/hub/pb/hub.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol Hub_Pb_APISignupCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APISignupCallBase: ClientCallUnaryBase<Hub_Pb_SignupRequest, Hub_Pb_SignupReply>, Hub_Pb_APISignupCall {
  override class var method: String { return "/hub.pb.API/Signup" }
}

internal protocol Hub_Pb_APISigninCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APISigninCallBase: ClientCallUnaryBase<Hub_Pb_SigninRequest, Hub_Pb_SigninReply>, Hub_Pb_APISigninCall {
  override class var method: String { return "/hub.pb.API/Signin" }
}

internal protocol Hub_Pb_APISignoutCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APISignoutCallBase: ClientCallUnaryBase<Hub_Pb_SignoutRequest, Hub_Pb_SignoutReply>, Hub_Pb_APISignoutCall {
  override class var method: String { return "/hub.pb.API/Signout" }
}

internal protocol Hub_Pb_APIGetSessionInfoCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIGetSessionInfoCallBase: ClientCallUnaryBase<Hub_Pb_GetSessionInfoRequest, Hub_Pb_GetSessionInfoReply>, Hub_Pb_APIGetSessionInfoCall {
  override class var method: String { return "/hub.pb.API/GetSessionInfo" }
}

internal protocol Hub_Pb_APICreateKeyCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APICreateKeyCallBase: ClientCallUnaryBase<Hub_Pb_CreateKeyRequest, Hub_Pb_GetKeyReply>, Hub_Pb_APICreateKeyCall {
  override class var method: String { return "/hub.pb.API/CreateKey" }
}

internal protocol Hub_Pb_APIListKeysCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIListKeysCallBase: ClientCallUnaryBase<Hub_Pb_ListKeysRequest, Hub_Pb_ListKeysReply>, Hub_Pb_APIListKeysCall {
  override class var method: String { return "/hub.pb.API/ListKeys" }
}

internal protocol Hub_Pb_APIInvalidateKeyCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIInvalidateKeyCallBase: ClientCallUnaryBase<Hub_Pb_InvalidateKeyRequest, Hub_Pb_InvalidateKeyReply>, Hub_Pb_APIInvalidateKeyCall {
  override class var method: String { return "/hub.pb.API/InvalidateKey" }
}

internal protocol Hub_Pb_APICreateOrgCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APICreateOrgCallBase: ClientCallUnaryBase<Hub_Pb_CreateOrgRequest, Hub_Pb_GetOrgReply>, Hub_Pb_APICreateOrgCall {
  override class var method: String { return "/hub.pb.API/CreateOrg" }
}

internal protocol Hub_Pb_APIGetOrgCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIGetOrgCallBase: ClientCallUnaryBase<Hub_Pb_GetOrgRequest, Hub_Pb_GetOrgReply>, Hub_Pb_APIGetOrgCall {
  override class var method: String { return "/hub.pb.API/GetOrg" }
}

internal protocol Hub_Pb_APIListOrgsCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIListOrgsCallBase: ClientCallUnaryBase<Hub_Pb_ListOrgsRequest, Hub_Pb_ListOrgsReply>, Hub_Pb_APIListOrgsCall {
  override class var method: String { return "/hub.pb.API/ListOrgs" }
}

internal protocol Hub_Pb_APIRemoveOrgCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIRemoveOrgCallBase: ClientCallUnaryBase<Hub_Pb_RemoveOrgRequest, Hub_Pb_RemoveOrgReply>, Hub_Pb_APIRemoveOrgCall {
  override class var method: String { return "/hub.pb.API/RemoveOrg" }
}

internal protocol Hub_Pb_APIInviteToOrgCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIInviteToOrgCallBase: ClientCallUnaryBase<Hub_Pb_InviteToOrgRequest, Hub_Pb_InviteToOrgReply>, Hub_Pb_APIInviteToOrgCall {
  override class var method: String { return "/hub.pb.API/InviteToOrg" }
}

internal protocol Hub_Pb_APILeaveOrgCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APILeaveOrgCallBase: ClientCallUnaryBase<Hub_Pb_LeaveOrgRequest, Hub_Pb_LeaveOrgReply>, Hub_Pb_APILeaveOrgCall {
  override class var method: String { return "/hub.pb.API/LeaveOrg" }
}

internal protocol Hub_Pb_APIIsUsernameAvailableCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIIsUsernameAvailableCallBase: ClientCallUnaryBase<Hub_Pb_IsUsernameAvailableRequest, Hub_Pb_IsUsernameAvailableReply>, Hub_Pb_APIIsUsernameAvailableCall {
  override class var method: String { return "/hub.pb.API/IsUsernameAvailable" }
}

internal protocol Hub_Pb_APIIsOrgNameAvailableCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIIsOrgNameAvailableCallBase: ClientCallUnaryBase<Hub_Pb_IsOrgNameAvailableRequest, Hub_Pb_IsOrgNameAvailableReply>, Hub_Pb_APIIsOrgNameAvailableCall {
  override class var method: String { return "/hub.pb.API/IsOrgNameAvailable" }
}

internal protocol Hub_Pb_APIDestroyAccountCall: ClientCallUnary {}

fileprivate final class Hub_Pb_APIDestroyAccountCallBase: ClientCallUnaryBase<Hub_Pb_DestroyAccountRequest, Hub_Pb_DestroyAccountReply>, Hub_Pb_APIDestroyAccountCall {
  override class var method: String { return "/hub.pb.API/DestroyAccount" }
}


/// Instantiate Hub_Pb_APIServiceClient, then call methods of this protocol to make API calls.
internal protocol Hub_Pb_APIService: ServiceClient {
  /// Synchronous. Unary.
  func signup(_ request: Hub_Pb_SignupRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_SignupReply
  /// Asynchronous. Unary.
  @discardableResult
  func signup(_ request: Hub_Pb_SignupRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_SignupReply?, CallResult) -> Void) throws -> Hub_Pb_APISignupCall

  /// Synchronous. Unary.
  func signin(_ request: Hub_Pb_SigninRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_SigninReply
  /// Asynchronous. Unary.
  @discardableResult
  func signin(_ request: Hub_Pb_SigninRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_SigninReply?, CallResult) -> Void) throws -> Hub_Pb_APISigninCall

  /// Synchronous. Unary.
  func signout(_ request: Hub_Pb_SignoutRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_SignoutReply
  /// Asynchronous. Unary.
  @discardableResult
  func signout(_ request: Hub_Pb_SignoutRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_SignoutReply?, CallResult) -> Void) throws -> Hub_Pb_APISignoutCall

  /// Synchronous. Unary.
  func getSessionInfo(_ request: Hub_Pb_GetSessionInfoRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetSessionInfoReply
  /// Asynchronous. Unary.
  @discardableResult
  func getSessionInfo(_ request: Hub_Pb_GetSessionInfoRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetSessionInfoReply?, CallResult) -> Void) throws -> Hub_Pb_APIGetSessionInfoCall

  /// Synchronous. Unary.
  func createKey(_ request: Hub_Pb_CreateKeyRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetKeyReply
  /// Asynchronous. Unary.
  @discardableResult
  func createKey(_ request: Hub_Pb_CreateKeyRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetKeyReply?, CallResult) -> Void) throws -> Hub_Pb_APICreateKeyCall

  /// Synchronous. Unary.
  func listKeys(_ request: Hub_Pb_ListKeysRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_ListKeysReply
  /// Asynchronous. Unary.
  @discardableResult
  func listKeys(_ request: Hub_Pb_ListKeysRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_ListKeysReply?, CallResult) -> Void) throws -> Hub_Pb_APIListKeysCall

  /// Synchronous. Unary.
  func invalidateKey(_ request: Hub_Pb_InvalidateKeyRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_InvalidateKeyReply
  /// Asynchronous. Unary.
  @discardableResult
  func invalidateKey(_ request: Hub_Pb_InvalidateKeyRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_InvalidateKeyReply?, CallResult) -> Void) throws -> Hub_Pb_APIInvalidateKeyCall

  /// Synchronous. Unary.
  func createOrg(_ request: Hub_Pb_CreateOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetOrgReply
  /// Asynchronous. Unary.
  @discardableResult
  func createOrg(_ request: Hub_Pb_CreateOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APICreateOrgCall

  /// Synchronous. Unary.
  func getOrg(_ request: Hub_Pb_GetOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetOrgReply
  /// Asynchronous. Unary.
  @discardableResult
  func getOrg(_ request: Hub_Pb_GetOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIGetOrgCall

  /// Synchronous. Unary.
  func listOrgs(_ request: Hub_Pb_ListOrgsRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_ListOrgsReply
  /// Asynchronous. Unary.
  @discardableResult
  func listOrgs(_ request: Hub_Pb_ListOrgsRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_ListOrgsReply?, CallResult) -> Void) throws -> Hub_Pb_APIListOrgsCall

  /// Synchronous. Unary.
  func removeOrg(_ request: Hub_Pb_RemoveOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_RemoveOrgReply
  /// Asynchronous. Unary.
  @discardableResult
  func removeOrg(_ request: Hub_Pb_RemoveOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_RemoveOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIRemoveOrgCall

  /// Synchronous. Unary.
  func inviteToOrg(_ request: Hub_Pb_InviteToOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_InviteToOrgReply
  /// Asynchronous. Unary.
  @discardableResult
  func inviteToOrg(_ request: Hub_Pb_InviteToOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_InviteToOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIInviteToOrgCall

  /// Synchronous. Unary.
  func leaveOrg(_ request: Hub_Pb_LeaveOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_LeaveOrgReply
  /// Asynchronous. Unary.
  @discardableResult
  func leaveOrg(_ request: Hub_Pb_LeaveOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_LeaveOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APILeaveOrgCall

  /// Synchronous. Unary.
  func isUsernameAvailable(_ request: Hub_Pb_IsUsernameAvailableRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_IsUsernameAvailableReply
  /// Asynchronous. Unary.
  @discardableResult
  func isUsernameAvailable(_ request: Hub_Pb_IsUsernameAvailableRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_IsUsernameAvailableReply?, CallResult) -> Void) throws -> Hub_Pb_APIIsUsernameAvailableCall

  /// Synchronous. Unary.
  func isOrgNameAvailable(_ request: Hub_Pb_IsOrgNameAvailableRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_IsOrgNameAvailableReply
  /// Asynchronous. Unary.
  @discardableResult
  func isOrgNameAvailable(_ request: Hub_Pb_IsOrgNameAvailableRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_IsOrgNameAvailableReply?, CallResult) -> Void) throws -> Hub_Pb_APIIsOrgNameAvailableCall

  /// Synchronous. Unary.
  func destroyAccount(_ request: Hub_Pb_DestroyAccountRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_DestroyAccountReply
  /// Asynchronous. Unary.
  @discardableResult
  func destroyAccount(_ request: Hub_Pb_DestroyAccountRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_DestroyAccountReply?, CallResult) -> Void) throws -> Hub_Pb_APIDestroyAccountCall

}

internal extension Hub_Pb_APIService {
  /// Synchronous. Unary.
  func signup(_ request: Hub_Pb_SignupRequest) throws -> Hub_Pb_SignupReply {
    return try self.signup(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func signup(_ request: Hub_Pb_SignupRequest, completion: @escaping (Hub_Pb_SignupReply?, CallResult) -> Void) throws -> Hub_Pb_APISignupCall {
    return try self.signup(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func signin(_ request: Hub_Pb_SigninRequest) throws -> Hub_Pb_SigninReply {
    return try self.signin(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func signin(_ request: Hub_Pb_SigninRequest, completion: @escaping (Hub_Pb_SigninReply?, CallResult) -> Void) throws -> Hub_Pb_APISigninCall {
    return try self.signin(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func signout(_ request: Hub_Pb_SignoutRequest) throws -> Hub_Pb_SignoutReply {
    return try self.signout(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func signout(_ request: Hub_Pb_SignoutRequest, completion: @escaping (Hub_Pb_SignoutReply?, CallResult) -> Void) throws -> Hub_Pb_APISignoutCall {
    return try self.signout(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getSessionInfo(_ request: Hub_Pb_GetSessionInfoRequest) throws -> Hub_Pb_GetSessionInfoReply {
    return try self.getSessionInfo(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getSessionInfo(_ request: Hub_Pb_GetSessionInfoRequest, completion: @escaping (Hub_Pb_GetSessionInfoReply?, CallResult) -> Void) throws -> Hub_Pb_APIGetSessionInfoCall {
    return try self.getSessionInfo(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func createKey(_ request: Hub_Pb_CreateKeyRequest) throws -> Hub_Pb_GetKeyReply {
    return try self.createKey(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func createKey(_ request: Hub_Pb_CreateKeyRequest, completion: @escaping (Hub_Pb_GetKeyReply?, CallResult) -> Void) throws -> Hub_Pb_APICreateKeyCall {
    return try self.createKey(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func listKeys(_ request: Hub_Pb_ListKeysRequest) throws -> Hub_Pb_ListKeysReply {
    return try self.listKeys(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func listKeys(_ request: Hub_Pb_ListKeysRequest, completion: @escaping (Hub_Pb_ListKeysReply?, CallResult) -> Void) throws -> Hub_Pb_APIListKeysCall {
    return try self.listKeys(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func invalidateKey(_ request: Hub_Pb_InvalidateKeyRequest) throws -> Hub_Pb_InvalidateKeyReply {
    return try self.invalidateKey(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func invalidateKey(_ request: Hub_Pb_InvalidateKeyRequest, completion: @escaping (Hub_Pb_InvalidateKeyReply?, CallResult) -> Void) throws -> Hub_Pb_APIInvalidateKeyCall {
    return try self.invalidateKey(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func createOrg(_ request: Hub_Pb_CreateOrgRequest) throws -> Hub_Pb_GetOrgReply {
    return try self.createOrg(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func createOrg(_ request: Hub_Pb_CreateOrgRequest, completion: @escaping (Hub_Pb_GetOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APICreateOrgCall {
    return try self.createOrg(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func getOrg(_ request: Hub_Pb_GetOrgRequest) throws -> Hub_Pb_GetOrgReply {
    return try self.getOrg(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func getOrg(_ request: Hub_Pb_GetOrgRequest, completion: @escaping (Hub_Pb_GetOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIGetOrgCall {
    return try self.getOrg(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func listOrgs(_ request: Hub_Pb_ListOrgsRequest) throws -> Hub_Pb_ListOrgsReply {
    return try self.listOrgs(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func listOrgs(_ request: Hub_Pb_ListOrgsRequest, completion: @escaping (Hub_Pb_ListOrgsReply?, CallResult) -> Void) throws -> Hub_Pb_APIListOrgsCall {
    return try self.listOrgs(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func removeOrg(_ request: Hub_Pb_RemoveOrgRequest) throws -> Hub_Pb_RemoveOrgReply {
    return try self.removeOrg(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func removeOrg(_ request: Hub_Pb_RemoveOrgRequest, completion: @escaping (Hub_Pb_RemoveOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIRemoveOrgCall {
    return try self.removeOrg(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func inviteToOrg(_ request: Hub_Pb_InviteToOrgRequest) throws -> Hub_Pb_InviteToOrgReply {
    return try self.inviteToOrg(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func inviteToOrg(_ request: Hub_Pb_InviteToOrgRequest, completion: @escaping (Hub_Pb_InviteToOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIInviteToOrgCall {
    return try self.inviteToOrg(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func leaveOrg(_ request: Hub_Pb_LeaveOrgRequest) throws -> Hub_Pb_LeaveOrgReply {
    return try self.leaveOrg(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func leaveOrg(_ request: Hub_Pb_LeaveOrgRequest, completion: @escaping (Hub_Pb_LeaveOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APILeaveOrgCall {
    return try self.leaveOrg(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func isUsernameAvailable(_ request: Hub_Pb_IsUsernameAvailableRequest) throws -> Hub_Pb_IsUsernameAvailableReply {
    return try self.isUsernameAvailable(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func isUsernameAvailable(_ request: Hub_Pb_IsUsernameAvailableRequest, completion: @escaping (Hub_Pb_IsUsernameAvailableReply?, CallResult) -> Void) throws -> Hub_Pb_APIIsUsernameAvailableCall {
    return try self.isUsernameAvailable(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func isOrgNameAvailable(_ request: Hub_Pb_IsOrgNameAvailableRequest) throws -> Hub_Pb_IsOrgNameAvailableReply {
    return try self.isOrgNameAvailable(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func isOrgNameAvailable(_ request: Hub_Pb_IsOrgNameAvailableRequest, completion: @escaping (Hub_Pb_IsOrgNameAvailableReply?, CallResult) -> Void) throws -> Hub_Pb_APIIsOrgNameAvailableCall {
    return try self.isOrgNameAvailable(request, metadata: self.metadata, completion: completion)
  }

  /// Synchronous. Unary.
  func destroyAccount(_ request: Hub_Pb_DestroyAccountRequest) throws -> Hub_Pb_DestroyAccountReply {
    return try self.destroyAccount(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func destroyAccount(_ request: Hub_Pb_DestroyAccountRequest, completion: @escaping (Hub_Pb_DestroyAccountReply?, CallResult) -> Void) throws -> Hub_Pb_APIDestroyAccountCall {
    return try self.destroyAccount(request, metadata: self.metadata, completion: completion)
  }

}

internal final class Hub_Pb_APIServiceClient: ServiceClientBase, Hub_Pb_APIService {
  /// Synchronous. Unary.
  internal func signup(_ request: Hub_Pb_SignupRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_SignupReply {
    return try Hub_Pb_APISignupCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func signup(_ request: Hub_Pb_SignupRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_SignupReply?, CallResult) -> Void) throws -> Hub_Pb_APISignupCall {
    return try Hub_Pb_APISignupCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func signin(_ request: Hub_Pb_SigninRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_SigninReply {
    return try Hub_Pb_APISigninCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func signin(_ request: Hub_Pb_SigninRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_SigninReply?, CallResult) -> Void) throws -> Hub_Pb_APISigninCall {
    return try Hub_Pb_APISigninCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func signout(_ request: Hub_Pb_SignoutRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_SignoutReply {
    return try Hub_Pb_APISignoutCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func signout(_ request: Hub_Pb_SignoutRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_SignoutReply?, CallResult) -> Void) throws -> Hub_Pb_APISignoutCall {
    return try Hub_Pb_APISignoutCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getSessionInfo(_ request: Hub_Pb_GetSessionInfoRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetSessionInfoReply {
    return try Hub_Pb_APIGetSessionInfoCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func getSessionInfo(_ request: Hub_Pb_GetSessionInfoRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetSessionInfoReply?, CallResult) -> Void) throws -> Hub_Pb_APIGetSessionInfoCall {
    return try Hub_Pb_APIGetSessionInfoCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func createKey(_ request: Hub_Pb_CreateKeyRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetKeyReply {
    return try Hub_Pb_APICreateKeyCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func createKey(_ request: Hub_Pb_CreateKeyRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetKeyReply?, CallResult) -> Void) throws -> Hub_Pb_APICreateKeyCall {
    return try Hub_Pb_APICreateKeyCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func listKeys(_ request: Hub_Pb_ListKeysRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_ListKeysReply {
    return try Hub_Pb_APIListKeysCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func listKeys(_ request: Hub_Pb_ListKeysRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_ListKeysReply?, CallResult) -> Void) throws -> Hub_Pb_APIListKeysCall {
    return try Hub_Pb_APIListKeysCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func invalidateKey(_ request: Hub_Pb_InvalidateKeyRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_InvalidateKeyReply {
    return try Hub_Pb_APIInvalidateKeyCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func invalidateKey(_ request: Hub_Pb_InvalidateKeyRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_InvalidateKeyReply?, CallResult) -> Void) throws -> Hub_Pb_APIInvalidateKeyCall {
    return try Hub_Pb_APIInvalidateKeyCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func createOrg(_ request: Hub_Pb_CreateOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetOrgReply {
    return try Hub_Pb_APICreateOrgCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func createOrg(_ request: Hub_Pb_CreateOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APICreateOrgCall {
    return try Hub_Pb_APICreateOrgCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getOrg(_ request: Hub_Pb_GetOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_GetOrgReply {
    return try Hub_Pb_APIGetOrgCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func getOrg(_ request: Hub_Pb_GetOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_GetOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIGetOrgCall {
    return try Hub_Pb_APIGetOrgCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func listOrgs(_ request: Hub_Pb_ListOrgsRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_ListOrgsReply {
    return try Hub_Pb_APIListOrgsCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func listOrgs(_ request: Hub_Pb_ListOrgsRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_ListOrgsReply?, CallResult) -> Void) throws -> Hub_Pb_APIListOrgsCall {
    return try Hub_Pb_APIListOrgsCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func removeOrg(_ request: Hub_Pb_RemoveOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_RemoveOrgReply {
    return try Hub_Pb_APIRemoveOrgCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func removeOrg(_ request: Hub_Pb_RemoveOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_RemoveOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIRemoveOrgCall {
    return try Hub_Pb_APIRemoveOrgCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func inviteToOrg(_ request: Hub_Pb_InviteToOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_InviteToOrgReply {
    return try Hub_Pb_APIInviteToOrgCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func inviteToOrg(_ request: Hub_Pb_InviteToOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_InviteToOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APIInviteToOrgCall {
    return try Hub_Pb_APIInviteToOrgCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func leaveOrg(_ request: Hub_Pb_LeaveOrgRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_LeaveOrgReply {
    return try Hub_Pb_APILeaveOrgCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func leaveOrg(_ request: Hub_Pb_LeaveOrgRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_LeaveOrgReply?, CallResult) -> Void) throws -> Hub_Pb_APILeaveOrgCall {
    return try Hub_Pb_APILeaveOrgCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func isUsernameAvailable(_ request: Hub_Pb_IsUsernameAvailableRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_IsUsernameAvailableReply {
    return try Hub_Pb_APIIsUsernameAvailableCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func isUsernameAvailable(_ request: Hub_Pb_IsUsernameAvailableRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_IsUsernameAvailableReply?, CallResult) -> Void) throws -> Hub_Pb_APIIsUsernameAvailableCall {
    return try Hub_Pb_APIIsUsernameAvailableCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func isOrgNameAvailable(_ request: Hub_Pb_IsOrgNameAvailableRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_IsOrgNameAvailableReply {
    return try Hub_Pb_APIIsOrgNameAvailableCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func isOrgNameAvailable(_ request: Hub_Pb_IsOrgNameAvailableRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_IsOrgNameAvailableReply?, CallResult) -> Void) throws -> Hub_Pb_APIIsOrgNameAvailableCall {
    return try Hub_Pb_APIIsOrgNameAvailableCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func destroyAccount(_ request: Hub_Pb_DestroyAccountRequest, metadata customMetadata: Metadata) throws -> Hub_Pb_DestroyAccountReply {
    return try Hub_Pb_APIDestroyAccountCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func destroyAccount(_ request: Hub_Pb_DestroyAccountRequest, metadata customMetadata: Metadata, completion: @escaping (Hub_Pb_DestroyAccountReply?, CallResult) -> Void) throws -> Hub_Pb_APIDestroyAccountCall {
    return try Hub_Pb_APIDestroyAccountCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol Hub_Pb_APIProvider: ServiceProvider {
  func signup(request: Hub_Pb_SignupRequest, session: Hub_Pb_APISignupSession) throws -> Hub_Pb_SignupReply
  func signin(request: Hub_Pb_SigninRequest, session: Hub_Pb_APISigninSession) throws -> Hub_Pb_SigninReply
  func signout(request: Hub_Pb_SignoutRequest, session: Hub_Pb_APISignoutSession) throws -> Hub_Pb_SignoutReply
  func getSessionInfo(request: Hub_Pb_GetSessionInfoRequest, session: Hub_Pb_APIGetSessionInfoSession) throws -> Hub_Pb_GetSessionInfoReply
  func createKey(request: Hub_Pb_CreateKeyRequest, session: Hub_Pb_APICreateKeySession) throws -> Hub_Pb_GetKeyReply
  func listKeys(request: Hub_Pb_ListKeysRequest, session: Hub_Pb_APIListKeysSession) throws -> Hub_Pb_ListKeysReply
  func invalidateKey(request: Hub_Pb_InvalidateKeyRequest, session: Hub_Pb_APIInvalidateKeySession) throws -> Hub_Pb_InvalidateKeyReply
  func createOrg(request: Hub_Pb_CreateOrgRequest, session: Hub_Pb_APICreateOrgSession) throws -> Hub_Pb_GetOrgReply
  func getOrg(request: Hub_Pb_GetOrgRequest, session: Hub_Pb_APIGetOrgSession) throws -> Hub_Pb_GetOrgReply
  func listOrgs(request: Hub_Pb_ListOrgsRequest, session: Hub_Pb_APIListOrgsSession) throws -> Hub_Pb_ListOrgsReply
  func removeOrg(request: Hub_Pb_RemoveOrgRequest, session: Hub_Pb_APIRemoveOrgSession) throws -> Hub_Pb_RemoveOrgReply
  func inviteToOrg(request: Hub_Pb_InviteToOrgRequest, session: Hub_Pb_APIInviteToOrgSession) throws -> Hub_Pb_InviteToOrgReply
  func leaveOrg(request: Hub_Pb_LeaveOrgRequest, session: Hub_Pb_APILeaveOrgSession) throws -> Hub_Pb_LeaveOrgReply
  func isUsernameAvailable(request: Hub_Pb_IsUsernameAvailableRequest, session: Hub_Pb_APIIsUsernameAvailableSession) throws -> Hub_Pb_IsUsernameAvailableReply
  func isOrgNameAvailable(request: Hub_Pb_IsOrgNameAvailableRequest, session: Hub_Pb_APIIsOrgNameAvailableSession) throws -> Hub_Pb_IsOrgNameAvailableReply
  func destroyAccount(request: Hub_Pb_DestroyAccountRequest, session: Hub_Pb_APIDestroyAccountSession) throws -> Hub_Pb_DestroyAccountReply
}

extension Hub_Pb_APIProvider {
  internal var serviceName: String { return "hub.pb.API" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/hub.pb.API/Signup":
      return try Hub_Pb_APISignupSessionBase(
        handler: handler,
        providerBlock: { try self.signup(request: $0, session: $1 as! Hub_Pb_APISignupSessionBase) })
          .run()
    case "/hub.pb.API/Signin":
      return try Hub_Pb_APISigninSessionBase(
        handler: handler,
        providerBlock: { try self.signin(request: $0, session: $1 as! Hub_Pb_APISigninSessionBase) })
          .run()
    case "/hub.pb.API/Signout":
      return try Hub_Pb_APISignoutSessionBase(
        handler: handler,
        providerBlock: { try self.signout(request: $0, session: $1 as! Hub_Pb_APISignoutSessionBase) })
          .run()
    case "/hub.pb.API/GetSessionInfo":
      return try Hub_Pb_APIGetSessionInfoSessionBase(
        handler: handler,
        providerBlock: { try self.getSessionInfo(request: $0, session: $1 as! Hub_Pb_APIGetSessionInfoSessionBase) })
          .run()
    case "/hub.pb.API/CreateKey":
      return try Hub_Pb_APICreateKeySessionBase(
        handler: handler,
        providerBlock: { try self.createKey(request: $0, session: $1 as! Hub_Pb_APICreateKeySessionBase) })
          .run()
    case "/hub.pb.API/ListKeys":
      return try Hub_Pb_APIListKeysSessionBase(
        handler: handler,
        providerBlock: { try self.listKeys(request: $0, session: $1 as! Hub_Pb_APIListKeysSessionBase) })
          .run()
    case "/hub.pb.API/InvalidateKey":
      return try Hub_Pb_APIInvalidateKeySessionBase(
        handler: handler,
        providerBlock: { try self.invalidateKey(request: $0, session: $1 as! Hub_Pb_APIInvalidateKeySessionBase) })
          .run()
    case "/hub.pb.API/CreateOrg":
      return try Hub_Pb_APICreateOrgSessionBase(
        handler: handler,
        providerBlock: { try self.createOrg(request: $0, session: $1 as! Hub_Pb_APICreateOrgSessionBase) })
          .run()
    case "/hub.pb.API/GetOrg":
      return try Hub_Pb_APIGetOrgSessionBase(
        handler: handler,
        providerBlock: { try self.getOrg(request: $0, session: $1 as! Hub_Pb_APIGetOrgSessionBase) })
          .run()
    case "/hub.pb.API/ListOrgs":
      return try Hub_Pb_APIListOrgsSessionBase(
        handler: handler,
        providerBlock: { try self.listOrgs(request: $0, session: $1 as! Hub_Pb_APIListOrgsSessionBase) })
          .run()
    case "/hub.pb.API/RemoveOrg":
      return try Hub_Pb_APIRemoveOrgSessionBase(
        handler: handler,
        providerBlock: { try self.removeOrg(request: $0, session: $1 as! Hub_Pb_APIRemoveOrgSessionBase) })
          .run()
    case "/hub.pb.API/InviteToOrg":
      return try Hub_Pb_APIInviteToOrgSessionBase(
        handler: handler,
        providerBlock: { try self.inviteToOrg(request: $0, session: $1 as! Hub_Pb_APIInviteToOrgSessionBase) })
          .run()
    case "/hub.pb.API/LeaveOrg":
      return try Hub_Pb_APILeaveOrgSessionBase(
        handler: handler,
        providerBlock: { try self.leaveOrg(request: $0, session: $1 as! Hub_Pb_APILeaveOrgSessionBase) })
          .run()
    case "/hub.pb.API/IsUsernameAvailable":
      return try Hub_Pb_APIIsUsernameAvailableSessionBase(
        handler: handler,
        providerBlock: { try self.isUsernameAvailable(request: $0, session: $1 as! Hub_Pb_APIIsUsernameAvailableSessionBase) })
          .run()
    case "/hub.pb.API/IsOrgNameAvailable":
      return try Hub_Pb_APIIsOrgNameAvailableSessionBase(
        handler: handler,
        providerBlock: { try self.isOrgNameAvailable(request: $0, session: $1 as! Hub_Pb_APIIsOrgNameAvailableSessionBase) })
          .run()
    case "/hub.pb.API/DestroyAccount":
      return try Hub_Pb_APIDestroyAccountSessionBase(
        handler: handler,
        providerBlock: { try self.destroyAccount(request: $0, session: $1 as! Hub_Pb_APIDestroyAccountSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol Hub_Pb_APISignupSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APISignupSessionBase: ServerSessionUnaryBase<Hub_Pb_SignupRequest, Hub_Pb_SignupReply>, Hub_Pb_APISignupSession {}

internal protocol Hub_Pb_APISigninSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APISigninSessionBase: ServerSessionUnaryBase<Hub_Pb_SigninRequest, Hub_Pb_SigninReply>, Hub_Pb_APISigninSession {}

internal protocol Hub_Pb_APISignoutSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APISignoutSessionBase: ServerSessionUnaryBase<Hub_Pb_SignoutRequest, Hub_Pb_SignoutReply>, Hub_Pb_APISignoutSession {}

internal protocol Hub_Pb_APIGetSessionInfoSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIGetSessionInfoSessionBase: ServerSessionUnaryBase<Hub_Pb_GetSessionInfoRequest, Hub_Pb_GetSessionInfoReply>, Hub_Pb_APIGetSessionInfoSession {}

internal protocol Hub_Pb_APICreateKeySession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APICreateKeySessionBase: ServerSessionUnaryBase<Hub_Pb_CreateKeyRequest, Hub_Pb_GetKeyReply>, Hub_Pb_APICreateKeySession {}

internal protocol Hub_Pb_APIListKeysSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIListKeysSessionBase: ServerSessionUnaryBase<Hub_Pb_ListKeysRequest, Hub_Pb_ListKeysReply>, Hub_Pb_APIListKeysSession {}

internal protocol Hub_Pb_APIInvalidateKeySession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIInvalidateKeySessionBase: ServerSessionUnaryBase<Hub_Pb_InvalidateKeyRequest, Hub_Pb_InvalidateKeyReply>, Hub_Pb_APIInvalidateKeySession {}

internal protocol Hub_Pb_APICreateOrgSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APICreateOrgSessionBase: ServerSessionUnaryBase<Hub_Pb_CreateOrgRequest, Hub_Pb_GetOrgReply>, Hub_Pb_APICreateOrgSession {}

internal protocol Hub_Pb_APIGetOrgSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIGetOrgSessionBase: ServerSessionUnaryBase<Hub_Pb_GetOrgRequest, Hub_Pb_GetOrgReply>, Hub_Pb_APIGetOrgSession {}

internal protocol Hub_Pb_APIListOrgsSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIListOrgsSessionBase: ServerSessionUnaryBase<Hub_Pb_ListOrgsRequest, Hub_Pb_ListOrgsReply>, Hub_Pb_APIListOrgsSession {}

internal protocol Hub_Pb_APIRemoveOrgSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIRemoveOrgSessionBase: ServerSessionUnaryBase<Hub_Pb_RemoveOrgRequest, Hub_Pb_RemoveOrgReply>, Hub_Pb_APIRemoveOrgSession {}

internal protocol Hub_Pb_APIInviteToOrgSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIInviteToOrgSessionBase: ServerSessionUnaryBase<Hub_Pb_InviteToOrgRequest, Hub_Pb_InviteToOrgReply>, Hub_Pb_APIInviteToOrgSession {}

internal protocol Hub_Pb_APILeaveOrgSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APILeaveOrgSessionBase: ServerSessionUnaryBase<Hub_Pb_LeaveOrgRequest, Hub_Pb_LeaveOrgReply>, Hub_Pb_APILeaveOrgSession {}

internal protocol Hub_Pb_APIIsUsernameAvailableSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIIsUsernameAvailableSessionBase: ServerSessionUnaryBase<Hub_Pb_IsUsernameAvailableRequest, Hub_Pb_IsUsernameAvailableReply>, Hub_Pb_APIIsUsernameAvailableSession {}

internal protocol Hub_Pb_APIIsOrgNameAvailableSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIIsOrgNameAvailableSessionBase: ServerSessionUnaryBase<Hub_Pb_IsOrgNameAvailableRequest, Hub_Pb_IsOrgNameAvailableReply>, Hub_Pb_APIIsOrgNameAvailableSession {}

internal protocol Hub_Pb_APIDestroyAccountSession: ServerSessionUnary {}

fileprivate final class Hub_Pb_APIDestroyAccountSessionBase: ServerSessionUnaryBase<Hub_Pb_DestroyAccountRequest, Hub_Pb_DestroyAccountReply>, Hub_Pb_APIDestroyAccountSession {}

